### ISSUE TITLE
Move Echo notifications back to page content area

### ISSUE THREAD

**Issue by Hutchy68** [Hutchy68/pivot#19]
Notifications are broken, pop-up on mobile useless, and really should be back in content area so a user sees them.

**Comment by Hutchy68** [comment]
Hi @kghbln 

I just released v1.0.1 to fix a majority of the Echo notification issues. Part of the issue is Echo split the notifications into 2 types, messages and alerts. Never accounted for the change. I didn't like the icons to the left of the page actions button so I placed them above. They will also be above site notifications if they are used or other banner types.

![captureechonotifnone](https://cloud.githubusercontent.com/assets/3527469/24083606/77783b48-0cb0-11e7-933e-273040c1d388.PNG)

Notice present

![captureechonotif](https://cloud.githubusercontent.com/assets/3527469/24083610/895d8a20-0cb0-11e7-8aeb-6e13d8d46053.PNG)

**Comment by kghbln** [comment]
> I just released v1.0.1 

just updated the website. 

>  I didn't like the icons to the left of the page actions button so I placed them above.

That's true and cool already. Why not add the icons to the top bar left to the user icon? This way the skin is loosing about 1 cm at the top.

**Comment by Hutchy68** [comment]
Hmm...

That might be an idea for v1.1.0. I have to take a real close look at it because space is at a premium. I did see talk of making that extension part of the core which means It will have to get more attention from skin developers.

One thing that's a bug but on Echo, if there's notification counts for messages and alerts clicking on one makes both disappear. Something is up with their JavaScript and they're removing the "unseen" class from both items on click instead of the specific container. Perhaps they fixed it in 1.28 and have not backported it yet? 

I guess at this point I'd like to see how it works and looks, before making any more major changes to it.

**Comment by kghbln** [comment]
> That might be an idea for v1.1.0.

This will be cool from my perspective.

> One thing that's a bug but on Echo

I believe to remember that they have rewritten parts of the code for 1.28 and later. However if they have done so they will usually not backport since it is "just" maintenance. There were other issues too.

> I guess at this point I'd like to see how it works and looks, before making any more major changes to it.

Fair enough.

**Comment by Hutchy68** [comment]
Just pushed a PR #24 to make sure notification info is hidden when printing.

**Comment by Hutchy68** [comment]
Oops, didn't mean to close. 😊

**Comment by Hutchy68** [comment]
Ok, this issue is taken care of with PR #32 and the bundled echo fixes. Closing, reopen if needed.

**Comment by kghbln** [comment]
Now live on [pivot wiki](https://pivot.wikiproject.net/wiki/Main_Page). If this is cool you could do v1.0.4
