### ISSUE TITLE
Doesn't support Notifications (icons not showing correctly at top bar)

### ISSUE THREAD

**Issue by jeffmcneill** [Hutchy68/pivot#29]
![screen shot 2017-04-22 at 22 42 54](https://cloud.githubusercontent.com/assets/3119827/25305856/290c1084-27ad-11e7-9477-47e916261193.png)

Looks like all of the Bell and most of the inbox icons are cut off

Vs. how this looks in Vector

![screen shot 2017-04-22 at 22 44 23](https://cloud.githubusercontent.com/assets/3119827/25305863/497e415c-27ad-11e7-9f83-fa3525342107.png)

![screen shot 2017-04-22 at 22 45 18](https://cloud.githubusercontent.com/assets/3119827/25305869/69d157aa-27ad-11e7-929f-779317f44400.png)

**Comment by Hutchy68** [comment]
What browser are you using? Other extensions? Do you have special CSS in common.css? This is how I see it in use.

**Comment by Hutchy68** [comment]
![img_1439](https://cloud.githubusercontent.com/assets/3527469/25309451/7afd93ca-279b-11e7-9b0e-d67c1cf080e0.PNG)

**Comment by Hutchy68** [comment]
If you are using the new release of Echo ( Oct 2016 ) it had some breaking changes compared to their June 2016 release. I'll be releasing an update as soon as I do some further testing.

**Comment by jeffmcneill** [comment]
Chrome Version 57.0.2987.133 (64-bit) on OSX 10.10. I've dug around for about 40 minutes and can't track down what it is causing the trouble exactly. Sorry but too much time on this.

**Comment by Hutchy68** [comment]
If you have a link, I will take a look. Also, pushed PR #32 which included fixes to Echo notifications and a small tweak to mw-indicators. Pull down the master branch to test.

**Comment by Hutchy68** [comment]
Closing, inactive and belief fixed to address changes to Echo extension.
