### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by Hutchy68** [Hutchy68/pivot#33]
Couple of housekeeping tasks

- [x] Rename COPYING to LICENSE? GitHub will add the license type to the top of the repository if it finds LICENSE in the root. Unless you specifically set the license file when the repository is created, COPYING will never be picked up as the alternate LICENSE file. LICENSE or COPYING works with MW when clicking on the license link under Special:Version. Example of a (MIT) license icon. GitHub should pickup the LICENSE and its text, then put the appropriate license type on the repository.
![image](https://cloud.githubusercontent.com/assets/3527469/25483444/db921df6-2b23-11e7-837b-d1d617eef589.png)
- [x] Add a CONTRIBUTING.md file. Keep it simple.
- [x] Add a PULL_REQUEST_TEMPLATE.md. Keep it really simple.
- [x] Use the `.github` directory. GitHub will detect template files in the `.github` hidden directory. Put CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, and (thanks to @kghbln) the ISSUE_TEMPLATE.md.

**Comment by kghbln** [comment]
> Rename COPYING to LICENSE? 

I think this is a rather significant shortcoming of @GitHub and a bug not to support COPYING. Actually it is defying reality. While MediaWiki supports both file names COPYING is probably used by 99%+ of all extensions including MediaWiki core. ([see also in general on this](http://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project)) In the end however it is just a matter of personal taste since both should be understood.

**Comment by Hutchy68** [comment]
I wonder if it's a feature request. Actually I wonder if it matters having both. Seems a little redundant though.

**Comment by Hutchy68** [comment]
Hmm, editing the COPYING file directly did pick up it is a LICENSE type file. The icon at the top still isn't showing but I wonder if it is a timing thing with GitHub.com. I'll wait and see.

**Comment by Hutchy68** [comment]
Testing, I figured out what GitHub.com wants to see. Any variation and detection fails.

**Comment by kghbln** [comment]
> Testing, I figured out what GitHub.com wants to see. Any variation and detection fails.

Good on one hand since standards are enforced. Bad since you have to find other way to credit over time. So the variation should perhaps be done in README.

**Comment by Hutchy68** [comment]
Closing and opening a new issue specific to how to license with attribution in BSD-2 see #37
