### ISSUE TITLE
Sessioning Error

### ISSUE THREAD

**Issue by IsaacDodd** [Hutchy68/pivot#40]
### Setup

- Browsers and versions:
- MediaWiki version: 1.28
- Database version:
- PHP version: PHP 5.6
- Pivot version: Latest
- Extension version (if connected to the issue):

### Issue

Hello, I'm having a problem with Pivot interfering with logging into the installation of MediaWiki. I contacted my hosting company, which has been very good with fixing such problems, and even they were not able to figure it out. Mediawiki allows for logging in without the Pivot skin. With the Pivot skin I get an error that prevents me from logging in.

**Comment by Hutchy68** [comment]
Hmm, that is strange. I have not encountered that error. Pivot isn't doing anything special, it is using the default login from MW core. 

What does the error say? Can you log out and browse around your wiki? Check to see if you are staying logged in and not really logging out?

I just ran into that issue on another site using vector. I had to delete my cookies and setting [$wgCookieDomain](https://www.mediawiki.org/wiki/Manual:$wgCookieDomain) seemed to fix it.

**Comment by Hutchy68** [comment]
One more thing. Can you log in and then switch to Pivot skin without issue?

**Comment by kghbln** [comment]
Never heard about this before either. If it is related to sessions I suggest to also add `$wgSessionCacheType = CACHE_DB;` to your "LocalSettings.php" file. You are not by chance using any extension which interacts with authentication?

**Comment by Hutchy68** [comment]
Yes, I did that too 😄

**Comment by Hutchy68** [comment]
What really worked was clearing my cookies in my browser. MW is doing some strange persistence. I could not log out of that site. It even showed me logged out but the message was login failure on login and miraculously I was logged in. I even logged out, closed browser, reopened and found still logged in.

**Comment by kghbln** [comment]
> I even logged out, closed browser, reopened and found still logged in.

This may also be a browser thing depending on your setup. e.g. Firefox keeps the stored website cache even if it gets closed. `$wgExtendedLoginCookieExpiration` and `$wgCookieExpiration` are another two friends here.

**Comment by IsaacDodd** [comment]
Thank you for all of your help! I was able to get it to work by changing
both the wgCookieDomain variable and also by setting wgMainCacheType to
CACHE_ANYTHING which solved it. Thanks once again! Great theme by the way,
please keep extending and working on it

Sincerely,
Isaac M. E. Dodd

**Comment by Hutchy68** [comment]
Solved
