### ISSUE TITLE
Unable to customize

### ISSUE THREAD

**Issue by shawngs** [Hutchy68/pivot#41]
### Setup

- Browsers and versions:
Safari v. 10.1.1
Chrome v. 58
Firefox Developer Edition v. 54.0a2
- MediaWiki version: 1.28.2
- Database version: MySQL v. 5.5.54-cl
- PHP version: 7.1.5 (cgi-fcgi)
- Pivot version: 1.0.5
- Extension version (if connected to the issue):

### Issue

I am unable to customize my site as described in https://pivot.wikiproject.net/wiki/Customizing. I have tried adding customizations to both MediaWiki:Pivot.css and MediaWiki:Common.css but the site continues to remain the default pivot color. I have cleared browser cache and tried on 3 separate browsers but the default color remains. Please let me know what I should be doing. Thank you!

**Comment by kghbln** [comment]
You have to make sure that the CSS is valid. [Pivot.css](https://wikinfosec.com/index.php?title=MediaWiki:Pivot.css) is e.g. missing a closing bracket

```css
ul.side-nav label {
    background: #517398;
    color: #fff;
    padding: .25em .5em;
```
The result is that everything after that line is being ignored no matter if it is correct or invalid syntax.

**Comment by Hutchy68** [comment]
Yes, thanks @kghbln you hit it right. @shawngs I see 2 missing closing brackets (`}`) in your CSS. If you fix them in MediaWiki:Pivot.css, then clear your cache, you should see your changes. You should also delete the Common.css page or blank it. It's double loading same code and missing same closing brackets too.

If you are caching pages using file caching you might have to delete the CSS file in the cache.

**Comment by shawngs** [comment]
Thank you @kghbln and @Hutchy68! It is working now.

**Comment by kghbln** [comment]
> It is working now.

Cool and thank you for using Pivot!

**Comment by Hutchy68** [comment]
Awesome 👍🏻
