### ISSUE TITLE
Visual editor button is missing

### ISSUE THREAD

**Issue by innosflew** [Hutchy68/pivot#44]
### Setup

- Browsers and versions: Latest Opera/Opera Beta/Google Chrome
- MediaWiki version: 1.29
- Database version: MySQL 5.7.19
- PHP version: 7
- Pivot version: 1.0.5
- Extension version (if connected to the issue): VisualEditor 0.1.0 (7a8b171)

### Issue

The button for the visual editor doesn't seem to show up when I click on the Actions tab. I only see the source editor. Is this a bug or is visual editor not supported yet?

**Comment by Hutchy68** [comment]
Do you have visual editor enabled for pivot skin. Check settings of visual editor as you must specify the skins which can use it.

**Comment by innosflew** [comment]
Where can I do that? I went to the page of the VisualEditor extension on mediawiki.org but I didn't find any section talking about how can I enable it for specific skins. The only part which talks about skins there is the Skin compatibility section, but that only says "_it should be compatible with any skin that uses the required HTML structure_".

**Comment by innosflew** [comment]
Oh never mind. I found a sub page briefly mentioning `$wgVisualEditorSupportedSkins`. I added this to my `LocalSettings.php` and now it works:
```
$wgVisualEditorSupportedSkins = array(
    'vector',
    'pivot'
);
```

**Comment by Hutchy68** [comment]
Closing and marking solved
