### ISSUE TITLE
Pages go white/blank on access

### ISSUE THREAD

**Issue by kmeyn** [Hutchy68/pivot#51]
### Setup

- Browsers and versions: Microsoft Edge 41.16299.15.0, Chrome  64.0.3282.140, Internet Explorer 11.192.16.299
- MediaWiki version: 1.30
- Database version: 10.0.24-MariaDB-1~trusty-wsrep
- Pivot version:  1.0.5
- Extension version (if connected to the issue): N/A

### Issue

Pages goes blank. Happens everywhere, front page, categories , articles. NB! not an issue in Firefox 58.0.1/58.0.2 64bit

What happens: trying to open a front page, a category or article with any of the browsers Page shows for a second, then goes blank.  

I've commented out out line 4 in Pivot.js as per tips in this forum. No impact on this symptom. 

Due to lack of (previously) working Fontawersome I temporarily put in Fontawesome in Pivot.skin-php
<script src="https://use.fontawesome.com/8f01a2df2d.js"></script>  This does not appear to make any difference re. the issue reported. I've commented it out, no difference, pages still go blank.

**Comment by kmeyn** [comment]
Temp solution? Added
$wgUseSiteJs= false;
to LocalSettings.php

tested OK

**Comment by Hutchy68** [comment]
You are probably seeing a mix of multiple issues. First, caching of CSS and JS. That would break things as you update files with clearing the cache of your browser and/or HTML files if you are using file caching. `$wgUseSiteJS = false` would mean stop loading `MediaWiki:Common.js` which would be cached and continue to load even if you commented it out and didn't clear everything. 

I've created a `develop` branch and as soon as @Tealk PR's #50 to it, I will merge it in and you can download and test the fixes which would include your original #47.

**Comment by kmeyn** [comment]
Thanks (sorry for late response on this)

**Comment by Hutchy68** [comment]
Closing, solved in develop branch. Releasing v2.0 soon
