### ISSUE TITLE
Branch Develop is Broken

### ISSUE THREAD

**Issue by Hutchy68** [Hutchy68/pivot#53]
### Setup

- Browsers and versions: Chrome Version 64.0.3282.140 (Official Build) (64-bit) and others
- MediaWiki version: 1.30 / 1.27
- Database version:
- PHP version:
- Pivot version: 2.0.0-dev
- Extension version (if connected to the issue):

### Issue
@Tealk 

`develop` branch is now completely broken with commit #52 

![image](https://user-images.githubusercontent.com/3527469/35990974-c3506c7e-0cd3-11e8-9902-0d0680987d53.png)

Haven't looked to it in depth yet, but there is a thrown js error early on. Need to back up and look at 

`skin.json` calls `"assets/stylesheets/font-awesome.min.css",` missing min.css file in assets. Should just be `font-awesome.css`.

You have...

```
$out->addHeadItem('font', '<link rel="preload" href="/skins/pivot/assets/fonts/fontawesome-
webfont.woff2?v=4.7.0" as="font" type="font/woff2" crossorigin="anonymous" />');
```
You are calling an `href` with a hard set link. What about those who use `w/` or `whatever/` directory to install MediaWiki.

Viewport was eliminated. Breaking mobile view now.

**Comment by Tealk** [comment]
> develop branch is now completely broken with commit #52

I don't know why there's a problem I use this branch atm without a problem.

> skin.json calls "assets/stylesheets/font-awesome.min.css", missing min.css file in assets. Should just be font-awesome.css.

I forgot to upload font-awesome.min.css

> You have...
$out->addHeadItem('font', '<link rel="preload" href="/skins/pivot/assets/fonts/fontawesome-
webfont.woff2?v=4.7.0" as="font" type="font/woff2" crossorigin="anonymous" />');
You are calling an href with a hard set link. What about those who use w/ or whatever/ directory to install MediaWiki.

the path is relative to the directory. It can't cause any problems

https://github.com/Tealk/pivot/tree/font-awesome_css
this version is currently running error-free for me

**Comment by Hutchy68** [comment]
>I don't know why there's a problem I use this branch atm without a problem.

>skin.json calls "assets/stylesheets/font-awesome.min.css", missing min.css file in assets. Should just be font-awesome.css.

`skin.json` missing resource, breaks everything, so yes the file you forgot to upload is necessary to keep things from breaking. It looks like your version is just a minified version of font-awesome.css. I just pushed back a few things to fix. You can PR the `...min.css` back and remove the old `font-awesome.css` file, but will have to tweak the `skin.json` file again. Missing the `left-canvas` in `fontawesome.css` too. 

>the path is relative to the directory. It can't cause any problems

It can and it did. `href="/skins...` would look for `domainname.com/skins/....` `href="/w/skins...` looks in the `domainname.com/w/skins/...` Yes, your call is relative, but relative to the domain. Not the true path of the domain if MW is installed in a directory not the root. 

```
href="'.$wgLocalStylePath.'/pivot
```
$wgLocalStylePath will automatically set the first of the relative path `/w/skins` or `/skins` or `/wiki/skins` or even `/wiki/w/skins` if someone placed a MediaWiki instance in a directory called `wiki` and still added a `w` directory in that. Could also use $wgStylePath which is the same as $wgLocalStylePath, `"{$wgScriptPath}/skins"` See, https://www.mediawiki.org/wiki/Manual:$wgLocalStylePath 

My only goal was to get `develop` working quickly if anyone wants to use or test it.

**Comment by Tealk** [comment]
> Missing the left-canvas in fontawesome.css too.

which `left-canvas`?

have add `{$wgScriptPath}` to Pivot.skin.php

**Comment by Hutchy68** [comment]
Pull down the branch changes. Some I already made.

**Comment by Hutchy68** [comment]
This branch is now fixed and I am going to release it after I finish here and as soon as I update the `CHANGELOG.md` file and set a version. I made some changes and pushed a new `README.md`. 

Changes in `README.md` was updating all the Features List and settings, adding and removing some. Need to document this on the live site too. Next couple of big changes on the PR #52 were updating all of Foundation's js to v5.5.3 and pulling in all their changes to their branch of Foundation 5. There were some improvements to address warnings of deprecation of in code. My developer console thanked me :wink: I called the version `v5.5.3master` just to denote the change.

Also, I added preload of Font Awesome as a feature. Another warning in develop console, preloading the font but not using it early. I also took these other things into consideration when adding it as a feature:

- MIME type server errors, fix your server if you can
- Fonts should load what the browser wants and specific browsers load the font based on what is best for them.
- woff2 is a standard most modern browsers are moving towards if they aren't there already. However, the browser should be able to load the font which it chooses to load, woff2, woff, ttf, etc.... see first point, fix MIME type output on your server.
