### ISSUE TITLE
Tabs doesn't appear

### ISSUE THREAD

**Issue by ingemarwiklund** [Hutchy68/pivot#55]
### Setup

- Browsers and versions: Chrome 64 bit, 63.0.3239.132
- MediaWiki version: 1.28.3
- Database version: 5.6.38
- PHP version: 5.6.33 (cgi-fcgi)
- Pivot version: 1.0.5
- Extension version (if connected to the issue): -

http://grundskoleboken.se/wiki/Special:Version

### Issue

I've just copy-pasted the code from the pivot homepage, but no tabs appear, just the text:

<a href="#panel1">Tab 1</a><a href="#panel2">Tab 2</a><a href="#panel3">Tab 3</a><a href="#panel4">Tab 4</a>
This is the first panel of the basic tab example. You can place all sorts of content here including a grid.

Code: http://grundskoleboken.se/wiki/Sandl%C3%A5dan

**Comment by Hutchy68** [comment]
Hey @ingemarwiklund 

Please take a look at https://pivot.wikiproject.net/wiki/Pivot_features#Explanations_of_Feature_Choices

You need to turn on tabs then everything should work as expected. Let me know.

**Comment by ingemarwiklund** [comment]
It was this row:
'usePivotTabs' => false − will prevent Foundation 5 tab coding to pass through HTML sanitizer, "true" will allow this.

That text row wasn't even included in the text I put in localsettings.php when I installed pivot.

Adding it under fixed navbar in the list solved the problem. Thanks a lot for fast response :)

		'fixedNavBar' => false,
		'usePivotTabs' => true,

**Comment by Hutchy68** [comment]
Answered, closing.
