### ISSUE TITLE
Content of tab start two rows beneath for each tab

### ISSUE THREAD

**Issue by ingemarwiklund** [Hutchy68/pivot#57]
### Setup

Browsers and versions: Chrome 64 bit, 63.0.3239.132
MediaWiki version: 1.28.3
Database version: 5.6.38
PHP version: 5.6.33 (cgi-fcgi)
Pivot version: 1.0.5
Extension version (if connected to the issue): -

### Issue

I am happy that the tab function works. I am, and I know that you work with Pivot for free and do a wonderful work too. Thanks for everything. I don't want you to think I'm ungrateful. 

There is an issue though. When I start filling the tabs with content, I realize that for each tab, the content jumps two rows further down even though I start it on the row direct below the div-tag on all three tabs.

You can see the effect here, even though the text is in swedish. http://grundskoleboken.se/wiki/Isbarnen,_utdrag_ur_roman_-_l%C3%A4sf%C3%B6rst%C3%A5else

This is a minor issue since I use just three tabs, but it would become quite ugly after five tabs or more.  If there is a quick fix, it would indeed be appreciated.

**Comment by Hutchy68** [comment]
You have a lot of white space (extra lines). Try removing all those so it looks like this:
```
<div class="content active" id="panel1">
Content
</div>
<div class="content active" id="panel2">
Content
</div>
```

By doing this:
```
<div class="content active" id="panel1">
Content
</div>


<div class="content active" id="panel2">
Content
</div>
```
You are adding in line breaks

**Comment by ingemarwiklund** [comment]
That was indeed a quick fix :)

Sorry for disturbing you. Everything works just fine with the tabs after removing all white space at the bottom of the tabs. A silly mistake from my side, I must say.

**Comment by Hutchy68** [comment]
No worries, marking as answered and closing.
