### ISSUE TITLE
Search results page - limited width

### ISSUE THREAD

**Issue by kmeyn** [Hutchy68/pivot#58]
### Setup

Browsers and versions: Microsoft Edge 41.16299.15.0, Chrome 64.0.3282.140, Internet Explorer 11.192.16.299
MediaWiki version: 1.30
Database version: 10.0.24-MariaDB-1~trusty-wsrep
Pivot version: 1.0.5
Extension version (if connected to the issue): N/A

### Issue
On our installation the search bar + search results only seems occupy a defined part of the browser window (38em). It does not expand beyond this limit, yet shrinks responsively whilst seen from a smaller browser window.

Is there any way to make it responsive like other page, or cover 75% of the width of the browser?

Thanks!

**Comment by Hutchy68** [comment]
This is another one of those settings MediaWiki is adding to output. Anyway, add

```
.mw-search-results {
	max-width: 100%;
}
```

To your page, `MediaWiki:Pivot.css` . Hard reload the page CTRL-R or if you are using file caching, make sure you delete the css files so they can regenerate.

You could also make `max-width: 66em` or whatever you want.

**Comment by kmeyn** [comment]
Perfect! Thanks very much! :)

**Comment by Hutchy68** [comment]
Great need to update this is actual `pivot.css` file. Added CSS tag & Bug

**Comment by Hutchy68** [comment]
Fixed with commit eb144a1. Pull `develop` branch to test it. Closing, reopen if necessary.
