### ISSUE TITLE
Personal section on the right no longer working

### ISSUE THREAD

**Issue by kghbln** [Hutchy68/pivot#59]
### Setup

- Browsers and versions: Firefox 58.0.2 and Chrome 64.0.3282.167
- MediaWiki | 1.27.4 (317104c)23:34, 7 February 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Pivot | 2.0.0 (3038a4c) 10:13, 4 May 2017

### Issue

After updating to v2.0.0 clicking on the user icon on the upper right to get the personal menu on the right no longer works. It does not move in. Console does not show issues.

See the [demo wiki](https://pivot.wikiproject.net/wiki/Special:Version).

**Comment by Hutchy68** [comment]
Actually, both are broken on mobile...left and right.

Can you make sure all files caches are cleared, js really important.

**Comment by Hutchy68** [comment]
Yep, all js is broken even actions menu. I am running 2.0.0 without the issues and cleared all cached files. Other site was not caching anything and no issues either.

**Comment by kghbln** [comment]
No, clearing the cache does not help at all. I switched to CACHE_NONE cleared the browser cache, disabled all related configuration settings but still I am seeing this issue.

**Comment by Hutchy68** [comment]
CDN? Not all the event listeners are loading. I don't see any errors in the console, but I did change the namespace of Foundation.js to match what it is now, 5.5.3master.

![image](https://user-images.githubusercontent.com/3527469/36802286-7f4859ec-1c82-11e8-83f9-57fc08834b51.png)

**Comment by kghbln** [comment]
I do not know what to do about this.

**Comment by Hutchy68** [comment]
Do you have a CDN in front of the server to deliver content. Cloudflare or something?

**Comment by kghbln** [comment]
> Do you have a CDN in front of the server to deliver content. Cloudflare or something?

No.

**Comment by Hutchy68** [comment]
I'm looking at debug=true for a comparison. It doesn't appear the js is loading at all from Foundation but there is no 404, missing or console errors being logged. Let me try this on 1.27 too. I'm testing 1.30

**Comment by Hutchy68** [comment]
Are you on master or develop? Did you pull down changes?

**Comment by kghbln** [comment]
> Are you on master or develop? Did you pull down changes?

I checked out v2.0.0 so I should be on master. I just checked out version 2.0.0 on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Main_Page) which is running MW 1.30.0 and moreover on the same server. It is working over there so most probably the new version is not compatible with MW 1.27.x

**Comment by Hutchy68** [comment]
Yep, checkout branch v1.x.x ( at least I had a fallback :wink: ) and revert the site back to v1. I need to look at why 1.27 is not allowing the js to load.

**Comment by Hutchy68** [comment]
....and I just updated the release to show need 1.30 until I figure out what the heck is going on.

**Comment by kghbln** [comment]
Will do. Yeah, having the 1.x branch was a very good idea.

**Comment by kghbln** [comment]
> ....and I just updated the release to show need 1.30 until I figure out what the heck is going on.

I will also be curious to see which version is breaking. Perhaps it works for 1.28 or 1.29 though 1.28 is obsolete anyways.

**Comment by Hutchy68** [comment]
Ok, try checking out master and pulling the changes. This commit should have fixed it 56a6ed08e79afd31b55ae78ecf159b54bdebc531 and I updated the release to point at the correct tag.

**Comment by kghbln** [comment]
> Ok, try checking out master and pulling the changes. This commit should have fixed it 56a6ed0 and I updated the release to point at the correct tag.

Done. Cool, Pivot is back in business for MW 1.27! You can now do the 2.0.1 release. I believe changing the tag of 2.0.0 is not semver.

**Comment by kghbln** [comment]
> You can now do the 2.0.1 release. I believe changing the tag of 2.0.0 is not semver.

Ah, already done the 2.0.0 way. I guess in future ... Anyways thanks a lot for tackling this issue!

**Comment by kghbln** [comment]
I am a bit confused now. When checking out v2.0.0 I should be getting https://github.com/Hutchy68/pivot/commit/15cce18901d673899fd36a15ca99bf3920a45480 as tagged but I am getting https://github.com/Hutchy68/pivot/commit/b4c88e79f30b9e9dc0ad7e10a89ccb53ecfb9368?

**Comment by Hutchy68** [comment]
Normally would have but.... ugh I should have released a beta first. Pretty excited to get it out and never imagined it would Bork 1.27. A bit easier to just update the tag since it was only a few hours.

**Comment by kghbln** [comment]
> Normally would have but.... ugh I should have released a beta first. 

No worries. It is sorted out now. :)

**Comment by Hutchy68** [comment]
For some reason it isn't hyperlinking like other extensions. One of mine...

![image](https://user-images.githubusercontent.com/3527469/36811551-31e9d440-1c9c-11e8-93cd-365b96921d92.png)

Foreground either

![image](https://user-images.githubusercontent.com/3527469/36812121-136cb01c-1c9e-11e8-8669-6ce425e9ca16.png)

I have noticed on GitHub repos, no hyperlinks and they are not updating. They do link and update to Phabricator commits.

**Comment by kghbln** [comment]
I think that extensions and skins must be in the WMF-repo to work with links.

**Comment by Hutchy68** [comment]
I agree but that means it must be hard coded in.

**Comment by kghbln** [comment]
> I agree but that means it must be hard coded in.

Not necessarily. When reporting an issue here GitHub detects the revision and links to it as seen in my report here: https://github.com/Hutchy68/pivot/issues/59#issue-301092971

**Comment by Hutchy68** [comment]
No I mean hardcoded in MediaWiki for specialpage.php and the output of Special:Version
