### ISSUE TITLE
Tabs not displayed

### ISSUE THREAD

**Issue by funes79** [Hutchy68/pivot#60]
### Setup

- Browsers and versions:
- MediaWiki version:
- Database version:
- PHP version:
- Pivot version:
- Extension version (if connected to the issue):

### Issue

Detailed description of the issue goes here.

I changed the default settings 

    $wgPivotDefaultFeatures = [
        'usePivotTabs' => true,
        'wikiNameDesktop' => 'Wiki name desktop'
    ];
    $wgDefaultSkin = 'pivot';
    $wgAllowSiteCSSOnRestrictedPages = true;
    $wgAllowUserCss = true;
    $wgHiddenPrefs[] = 'skin';

but instead of Tabs the page displays this:

    <a href="#panel1">Tab 1</a><a href="#panel2">Tab 2</a><a href="#panel3">Tab 3</a><a href="#panel4">Tab 4</a>
    Lorem ipsum dolor sit amet, ornare neque quisque etiam posuere voluptatem erat, scelerisque ornare tellus duis arcu eget ullamcorper. Lectus orci tincidunt augue tristique. Libero mus augue tortor urna, mauris sollicitudin fusce vestibulum nec, erat blandit in placerat ultrices, facilisis interdum consectetuer. Maecenas in unde, dolor a est ornare placerat dicta, ut nostra. Vehicula aliquam erat arcu. Nibh integer vestibulum natoque lacinia quis. A felis euismod sapien, eu dapibus, adipiscing in risus fringilla, hendrerit maecenas in dolor, vel nullam a.

**Comment by Hutchy68** [comment]
What kind of caching are you using? Did you clear it? Ex, File cache? Delete cache files.

**Comment by funes79** [comment]
It is a fresh install, using file cache. But cannot find anything in cache dir or /tmp.

    [root@ip-10-197-10-28 dev]# cat LocalSettings-dev.php  | grep Cache
    $wgMainCacheType = CACHE_NONE;
    $wgMemCachedServers = [];
    ## Set $wgCacheDirectory to a writable directory on the web server
    #$wgCacheDirectory = "$IP/cache";
    $wgCacheDirectory = "tmp/mediawiki_dev_cache";
    [root@ip-10-197-10-28 dev]#
    [root@ip-10-197-10-28 dev]# cat LocalSettings-dev.php  | grep cache
    #$wgCacheDirectory = "$IP/cache";
    $wgCacheDirectory = "tmp/mediawiki_dev_cache";
    [root@ip-10-197-10-28 dev]#
    [root@ip-10-197-10-28 dev]# ls -l ./cache
    total 0
    [root@ip-10-197-10-28 dev]# pwd
    /var/www/dev
    [root@ip-10-197-10-28 dev]# ls -l /tmp
    <empty>

**Comment by Hutchy68** [comment]
That cache directory is for localisation. `$wgUseFileCache` explicitly must be set to true. Then the default is `$wgFileCacheDirectory` is `"{$wgUploadDirectory}/cache"` which would be under your images. Since it didn't grep, assuming not using it.

Quick test, open an incognito browser window to the url you are using on dev and check results.

????
Browsers and versions:
MediaWiki version:
Database version:
PHP version:
Pivot version:
Extension version (if connected to the issue):

Using `1.30.0 (4c97eee) 20:35, 2 March 2018` tabs works fine for me.

![image](https://user-images.githubusercontent.com/3527469/37556785-35039cf0-29d1-11e8-972c-6da5c97811df.png)

**Comment by Hutchy68** [comment]
Oh, check output buffering too. php.ini and make sure it is set to something and not `Off`

**Comment by funes79** [comment]
The page does not understand/interpret the \<ul class="tabs" data-tab> <li class="tab-title activ" in incognito mode.
I changed the Localsettings:

    [root@ip-10-197-10-28 dev]# cat LocalSettings-dev.php | grep Cache | grep -v '^#'
    $wgMainCacheType = CACHE_NONE;
    $wgMemCachedServers = [];
    $wgCacheDirectory = "tmp/mediawiki_dev_cache";
    $wgUseFileCache = true;
    $wgFileCacheDirectory = "{$wgUploadDirectory}/cache";

    [root@ip-10-197-10-28 dev]# cat LocalSettings-dev.php | grep Upload | grep -v '^#'
    $wgEnableUploads = true;
    $wgUploadDirectory = "$IP/images_dev";
    $wgUploadPath = "/dev/images_dev";
    $wgFileCacheDirectory = "{$wgUploadDirectory}/cache";

    [root@ip-10-197-10-28 dev]# cat /etc/php.ini | grep buffering | grep -v '^;'
    output_buffering = 4096


MediaWiki | 1.30.0
PHP | 5.6.34 (apache2handler)
MySQL | 5.7.17-log

What should I do now?

**Comment by funes79** [comment]
And I tried to delete the local cache rm -rf ./images_dev/cache But didnt helped.

**Comment by Hutchy68** [comment]
Oops, just noticed you have `$wgPivotDefaultFeatures`. Change it to:
```
$wgPivotFeatures = [
    'usePivotTabs' => true,
    'wikiNameDesktop' => 'Wiki name desktop'
];
```

**Comment by funes79** [comment]
Yes, that was it!
Thanks for the help. After the change from wgPivotDefaultFeatures to wgPivotFeatures I had to clear the cache and then the tabs displayed.
Thanks

**Comment by Hutchy68** [comment]
Great... closing
