### ISSUE TITLE
Easy way to change overall color theme?

### ISSUE THREAD

**Issue by poVoq** [Hutchy68/pivot#64]
Hi!

I really like the overall functionality of this theme... but the mint-green isn't really to my liking :)

Is there an relatively easy way (preferably one that survives updates) to change some of the colors?

Thanks for the help.

**Comment by Hutchy68** [comment]
See https://pivot.wikiproject.net/wiki/Customizing and adding to `MediaWiki:Pivot.css` will not be effected by updates. Just make sure you reload css with CTRL-F5.

**Comment by poVoq** [comment]
Ahh totally overlooked that page. Sorry for that.

Works nicely, just had to add this:
```
/* Namespace label color */
h4.namespace.label {
    background-color: #3498DB;
}
```

**Comment by poVoq** [comment]
Hmm... is it possible that the responsive sidebar menus of the mobile view are controlled differently?
I tried overriding the "canvas-menu" background color on the above page, but it doesn't seem to have an effect.
