### ISSUE TITLE
Special:Preferences unaffected by pivot.css changes 

### ISSUE THREAD

**Issue by poVoq** [Hutchy68/pivot#65]
### Setup

- Browsers and versions: Firefox (latest)
- MediaWiki version: 1.30
- Pivot version: 2.0.0

### Issue

I changed the color styling via the MediaWiki:Pivot.css page and it works fine for all pages except the Special:Preferences page where the old color-scheme comes back up.

Any idea what could be causing this and how I could fix it? Thanks!

**Comment by Hutchy68** [comment]
https://www.mediawiki.org/wiki/Manual:$wgAllowSiteCSSOnRestrictedPages

**Comment by poVoq** [comment]
Thanks... sorry still new to MediaWiki.
