### ISSUE TITLE
Uncaught Errors: Module Already Implemented

### ISSUE THREAD

**Issue by SWAIDesign** [Hutchy68/pivot#75]
### Setup

- Browsers and versions: Chrome, Edge, Firefox
- MediaWiki version: 1.32.0
- Database version: 5.6.39-cll-lve - MySQL Community Server
- PHP version: 7.2
- Pivot version: 2.0.0
- Extension version (if connected to the issue):

### Issue

Detailed description of the issue goes here.

Sidebars not loading on fresh Wiki install: **https://wiki.ftxgames.com**. Consoles show the following:

**Chrome:**
`Uncaught Error: module already implemented: user.options
    at Object.implement (VM3943 load.php:19)
    at Main_Page:119
    at Array.RLQ.push (VM3943 load.php:42)
    at VM3943 load.php:42
    at VM3943 load.php:42
implement @ VM3943 load.php:19
(anonymous) @ Main_Page:119
RLQ.push @ VM3943 load.php:42
(anonymous) @ VM3943 load.php:42
(anonymous) @ VM3943 load.php:42
load.php?debug=false&lang=en&modules=skins.pivot.js&only=scripts&skin=pivot:1 Uncaught ReferenceError: jQuery is not defined
    at load.php?debug=false&lang=en&modules=skins.pivot.js&only=scripts&skin=pivot:1
    at load.php?debug=false&lang=en&modules=skins.pivot.js&only=scripts&skin=pivot:1
(anonymous) @ load.php?debug=false&lang=en&modules=skins.pivot.js&only=scripts&skin=pivot:1
(anonymous) @ load.php?debug=false&lang=en&modules=skins.pivot.js&only=scripts&skin=pivot:1
load.php?debug=false&lang=en&modules=jquery%2Csite|jquery.accessKeyLabel%2CcheckboxShiftClick%2Cclient%2CgetAttrs%2ChighlightText%2Csuggestions|mediawiki.RegExp%2CString%2CTitle%2Capi%2Cbase%2Ccldr%2CjqueryMsg%2Clanguage%2Cnotify%2CsearchSuggest%2Cstorage%2Cuser%2Cutil|mediawiki.action.view.rightClickEdit|mediawiki.libs.pluralruleparser|mediawiki.page.ready%2Cstartup|mediawiki.page.watch.ajax|user.defaults&skin=pivot&version=18u7pfi:141 JQMIGRATE: Migrate is installed with logging active, version 3.0.1
Main_Page:1 GET https://wiki.ftxgames.com/index.php/Main_Page 500 (Internal Server Error)`

**Firefox:**
`Error: module already implemented: user.tokens load.php:19:292
implement
https://wiki.ftxgames.com/load.php:19:292
<anonymous>
https://wiki.ftxgames.com/index.php/Main_Page:111:1501
RLQ.push
https://wiki.ftxgames.com/load.php:42:630
<anonymous>
https://wiki.ftxgames.com/load.php:42:686
<anonymous>
https://wiki.ftxgames.com/load.php:24:378
ReferenceError: jQuery is not defined[Learn More] load.php:1:100
<anonymous>
https://wiki.ftxgames.com/load.php:1:100
<anonymous>
https://wiki.ftxgames.com/load.php:1:2
JQMIGRATE: Migrate is installed with logging active, version 3.0.1`

I'm at a loss after trying re-installs and working on my server to check settings.

**Comment by Hutchy68** [comment]
Please don’t use 1.32 it was just released.  The skin will need an update which will probably cause a version bump in pivot.

**Comment by SWAIDesign** [comment]
Alright! Thanks. Got ahead of myself with this first time install of MediaWiki. Works fine now.

**Comment by kghbln** [comment]
Just yesterday I realized that Pivot is not working for 1.32 but @SWAIDesign was faster to report. Thanks a lot. I [updated mediawiki.org](https://www.mediawiki.org/w/index.php?title=Skin%3APivot&type=revision&diff=3063828&oldid=2935989) and [pivot.wikiproject.net](https://pivot.wikiproject.net/w/index.php?title=Main_Page&type=revision&diff=309&oldid=242) to provide an info about this.

I guess this issue should remain open until a fix was provided and released. Once this is done I will update the docu again.

@Hutchy68 <pivot.wikiproject.net> is still on MW 1.27. I will upgrade soon to MW 1.31.

**Comment by r2d02** [comment]
I'm also kindly requesting to re-open this issue. 

MW 1.32 wasn't "just released" as noted by @Hutchy68, it has been released 3 months ago and is currently the latest stable release of MW. So this should be treated as an issue.

Thank you @kghbln for updating mediawiki.org and pivot.wikiproject.net.

**Comment by Hutchy68** [comment]
The 1.32.0 stable release was released on 10 January 2019.

**Comment by r2d02** [comment]
> MW 1.32 wasn't "just released" as noted by @Hutchy68, it has been released 3 months ago and is currently the latest stable release of MW. So this should be treated as an issue.

Obivously it has been "branched from git master" on 2018-10-16 , the release was indeed on January 10th 2019.

**Comment by Hutchy68** [comment]
That might have been alpha then beta then rc. Stable means ready for production use is what I’m getting at. Besides 1.32 is a STS so, while I will look into what is going on, it will not be a rush.

**Comment by latindancer** [comment]
Hello,

Can you please let me know what the status of this issue is for MW 1.32?

Thanks

**Comment by kghbln** [comment]
> https://github.com/Hutchy68/pivot/issues/75#issuecomment-456741960

@Hutchy68 <pivot.wikiproject.net> is now on MW 1.31. Here Pivot is till working.

**Comment by latindancer** [comment]
Any update on this issue? Are you going to have it fix for MW 1.32?

**Comment by Hutchy68** [comment]
See #78. Still working on a fix as to why js is executing before jQuery is loaded.

**Comment by latindancer** [comment]
@Hutchy68 Thanks for the update :)

**Comment by Hutchy68** [comment]
Fixed in Release v2.1.0
