### ISSUE TITLE
Pivot broken in MW 1.32, jquery is not loading before scripts execute

### ISSUE THREAD

**Issue by Hutchy68** [Hutchy68/pivot#78]
### Setup

- Browsers and versions: Chrome, Firefox and Edge
- MediaWiki version: 1.32
- Database version:
- PHP version:
- Pivot version: 2.1.0
- Extension version (if connected to the issue):

### Issue

@paladox #74 

For some reason jquery is not loading from `/resources/lib/jquery/` in MW 1.32 before the bottom scripts are executed. I can see it in the waterfall as loaded, but the bottom scripts are not honoring the dependencies need. In Foreground, same waterfall, but it is waiting for the jquery.js to load and be available.

Working skin.json file

```
{
	"name": "Pivot",
	"version": "2.1.0",
	"author": [
		"Tom Hutchison",
		"..."
	],
	"license-name": "BSD-2-Clause",
	"url": "http://github.com/hutchy68/pivot",
	"descriptionmsg": "pivot-desc",
	"type": "skin",
	"ValidSkinNames": {
		"pivot": "Pivot"
	},
	"MessagesDirs": {
		"Skinpivot": [
			"i18n"
		]
	},
	"AutoloadClasses": {
		"SkinPivot": "Pivot.skin.php"
	},
	"ResourceModules": {
		"skins.pivot.styles": {
			"position": "top",
			"styles": [
				"assets/stylesheets/normalize.css",
				"assets/stylesheets/font-awesome.css",
				"assets/stylesheets/foundation.css",
				"assets/stylesheets/pivot.css",
				"assets/stylesheets/fontawsome.css",
				"assets/stylesheets/pivot-print.css"
			]
		},
		"skins.pivot.modernizr": {
			"position": "top",
			"scripts": [
				"assets/scripts/vendor/modernizr.js"
			]
		},
		"skins.pivot.js": {
			"position": "bottom",
			"scripts": [	
				"assets/scripts/vendor/jquery3.js",
				"assets/scripts/vendor/fastclick.js",
				"assets/scripts/vendor/placeholder.js",
				"assets/scripts/foundation/foundation.js",
				"assets/scripts/foundation/foundation.topbar.js",
				"assets/scripts/foundation/foundation.dropdown.js",
				"assets/scripts/foundation/foundation.joyride.js",
				"assets/scripts/foundation/foundation.accordion.js",
				"assets/scripts/foundation/foundation.offcanvas.js",
				"assets/scripts/foundation/foundation.alert.js",
				"assets/scripts/foundation/foundation.clearing.js",
				"assets/scripts/foundation/foundation.equalizer.js",
				"assets/scripts/foundation/foundation.interchange.js",
				"assets/scripts/foundation/foundation.orbit.js",
				"assets/scripts/foundation/foundation.reveal.js",
				"assets/scripts/foundation/foundation.tab.js",
				"assets/scripts/foundation/foundation.tooltip.js",
				"assets/scripts/foundation/foundation.magellan.js",
				"assets/scripts/pivot.js"
			],
			"dependencies": [
				"skins.pivot.modernizr",
				"jquery.cookie"
			]
		}
	},
	"ResourceFileModulePaths": {
		"localBasePath": "",
		"remoteSkinPath": "pivot"
	},
	"config": {},
	"manifest_version": 1
}
```

**Comment by Hutchy68** [comment]
Eureka!! I’ll be pushing out a working Pivot skin for MW 1.32 later tonight.

**Comment by Hutchy68** [comment]
Published release v2.1.0

**Comment by kghbln** [comment]
> Published release v2.1.0

@Hutchy68 Thanks a lot for the release! I just updated the demo wiki as well as the docu on it and on mediawiki.org. Also updated a wiki already on MW 1.32 and all in fluff too. :)

**Comment by Hutchy68** [comment]
Awesome! Thanks for all the extra work on mediawiki.org and wikiproject.net. I am going to add a link to pivot.wikiproject.net for extra documentation on the reader.md file.

**Comment by kghbln** [comment]
> Thanks for all the extra work on mediawiki.org and wikiproject.net.

You are welcome.

>  I am going to add a link to pivot.wikiproject.net for extra documentation on the reader.md file.

Great idea. In the end pivot.wikiproject.net still needs more docu love, e.g. I do not really know what "Smart Typography" stands for.
