### ISSUE TITLE
Header colour and footer area

### ISSUE THREAD

**Issue by LLCoolJayB** [Hutchy68/pivot#80]
### Setup

- Browsers and versions: Firefox and Google Chrome
- MediaWiki version: 1.27.5
- Database version: 
- PHP version: 5.6.40 (cgi-fgi)
- Pivot version: 2.1.0
- Extension version (if connected to the issue):

### Issue

I've recently installed Pivot, however, when editing my main page - the headers don't show the blue colour. 

The footer area also takes up the entire bottom part of the page, and is not limited to the main section, excluding the sidebar.

I have copied the source from the Pivot wiki page [on my wiki's sandbox page](https://lawlibwiki.com/index.php?title=Sandbox) to demonstrate this.

Appreciate any thoughts on this!

**Comment by Hutchy68** [comment]
Looks like you have multiple div closings without an opening div and the last two divs have no div closings.

**Comment by Hutchy68** [comment]
In your page markup to be clear.

**Comment by LLCoolJayB** [comment]
What do you mean? The sandbox page? The markup has been copied from the Pivot wiki.

My current main page is pre-Pivot install - I haven't changed anything.

**Comment by Hutchy68** [comment]
This looks fine on your sandbox page and the way it is supposed to look.
![image](https://user-images.githubusercontent.com/3527469/59967574-ff26a100-94f9-11e9-8ce9-7be2b0458fcc.png)

Exactly how the layout is supposed to look, this is on pivot.wikiproject.net
![image](https://user-images.githubusercontent.com/3527469/59967591-2d0be580-94fa-11e9-81c8-04a9f3e62fb1.png)

Your main page... is not right...
![image](https://user-images.githubusercontent.com/3527469/59967605-69d7dc80-94fa-11e9-83dd-11729ce57de7.png)

You have 3 unclosed div elements in the markup.
![image](https://user-images.githubusercontent.com/3527469/59967640-fa162180-94fa-11e9-9dbe-f641e700b0a0.png)

Fix the closing of those div elements in the markup and post back.

**Comment by LLCoolJayB** [comment]
Thanks, I'll get sorting that out - but I was planning to change the mainpage entirely using the Pivot tabs and table format so that it is cleaner looker.

What about the headers? Why aren't these working?

![image](https://user-images.githubusercontent.com/52108740/59967716-19767400-9526-11e9-89e3-e2398a530b27.png)

**Comment by Hutchy68** [comment]
Ah, now I understand what you are looking at for headers.

See, https://pivot.wikiproject.net/wiki/MediaWiki:Pivot.css

There is a piece of css to add the subheader class.
```
/* make the main page subheaders solid bars */
.subheader {
    background: #517398;
    color: #fff;
    text-align: center;
    padding: .5em;
}
```

**Comment by LLCoolJayB** [comment]
Perfect, you're a star! Thank you!
