### ISSUE TITLE
Search autocomplete not available on small screens

### ISSUE THREAD

**Issue by Amousey** [Hutchy68/pivot#85]
### Version 2.1.0

- Small screens, as defined by pivot css

### Issue

Small screens have different functionality for searching, and unlike the regular screen sizes small screens do not use autocomplete. This makes searching more awkward.

Special:Search does autocomplete on small screens.

Setting autocomplete on in the php below for `ul.side-nav` has no effect 

`<input type="search" name="search" placeholder="<?php echo wfMessage( 'search' )->text() ?>" title="Search [alt-shift-f]" accesskey="f" id="searchInput" autocomplete="on">`

**Comment by Hutchy68** [comment]
`autocomplete="on"` is not for autocomplete on search. It is to remember the form content at a browser level. It should be left off.

Looks like we can use the `mediawiki.searchSuggest.js` of core as it allows for generic skin adaptation (CologneBlue) of multi search forms on same page as it is in Pivot.

Find

https://github.com/Hutchy68/pivot/blob/078f9c258c4869432256e03eba5af44a3f6768bd/Pivot.skin.php#L122

an change `id="searchInput-offcanvas"` to `class="mw-searchInput"`

and you can do the same in

https://github.com/Hutchy68/pivot/blob/078f9c258c4869432256e03eba5af44a3f6768bd/Pivot.skin.php#L167

Also, should designate 

https://github.com/Hutchy68/pivot/blob/078f9c258c4869432256e03eba5af44a3f6768bd/Pivot.skin.php#L164

`id="searchform"` to `id="searchform-sidebar"`

**Comment by Hutchy68** [comment]
Fixed with commit eb144a1. Pull `develop` branch to test it. Closing, reopen if necessary.
