### ISSUE TITLE
Personal tools menu name not translated into other languages

### ISSUE THREAD

**Issue by Amousey** [Hutchy68/pivot#88]
### Setup

- Browsers and versions:
- MediaWiki version:
- Database version:
- PHP version:
- Pivot version:
- Extension version (if connected to the issue):

### Issue

Detailed description of the issue goes here.

**Comment by Amousey** [comment]
**Setup**
-Safari 
-MW 1.30
-Pivot 2.1.0
-MediaWiki:Licenses uses `TOOLBOX` to refer to the personal tools menu 

**English **
Personal tools menu is called Personal 

**German, Spanish, French **
Personal tools menu is called Personal but items below it and other haunts are fine 

**System messages **
MediaWiki:Personaltools    contains Personal tools
MediaWiki:Personaltools/de    contains Meine Werkzeuge

I don't recall renaming the Personal Tools menu to Personal and can't see where this option would be set, but clearly it's not using the system message.

Secondly, layout in Arabic on a mobile device (device width 375px) gives a three column effect, with the page layout too poor to read (however In not concerned dog this).

**Comment by Hutchy68** [comment]
Yes it should use the system message and no it does not. Will fix.

**Comment by Hutchy68** [comment]
Fixed with commit eb144a1. Pull `develop` branch to test it. Closing, reopen if necessary.
