### ISSUE TITLE
Syntax error in pivot.css

### ISSUE THREAD

**Issue by Amousey** [Hutchy68/pivot#89]
### Setup

- Browsers and versions: All
- Pivot version: 2.0.0

### Issue

Error when validating pivot.css code against w3c css validator.
`h4,h5,h6 {color: 2e2e2e;}`

### Suggested fix

`h4,h5,h6 {color: #2e2e2e;}`

**Comment by Hutchy68** [comment]
Fixed with commit eb144a1. Pull `develop` branch to test it. Closing, reopen if necessary.
