### ISSUE TITLE
Not Compatible with MW 1.34.1 - Error 500 (fresh install, no extensions)

### ISSUE THREAD

**Issue by designnerd** [Hutchy68/pivot#94]
### Setup

- Browsers and versions: All
- MediaWiki version: 1.34.1
- Database version: MySQL | 5.7.28-log
- PHP version: 7.3.15 (cgi-fcgi)
- Pivot version: 2.1.0
- Extension version (if connected to the issue): None installed or enabled, default without even default extensions enabled. Only thing enabled is uploads. 

### Issue

Not compatible with MW 1.34.1, kicks error 500 in preview, when activated. Had to use the following command in SSH to clear it out of user preferences to be able to access my site again: php userOptions.php skin --old "pivot" --new "vector"
Have to switch to a different skin despite how much we love this one, support for 1.33 is ending June 2020. Going to mess up all the pages we have grids in and this makes us very, very sad. Might port the grid and styles out of this theme into another. :<
Thank you for this wonderful skin, we hope to return to it in the future.

**Comment by Hutchy68** [comment]
I’ll be adding a fix for that in 24 hrs. Known issue because of change in MW.

**Comment by Hutchy68** [comment]
Fixed with release v2.2.0, pull master (2.2.0) or develop (2.2.0-dev)

**Comment by designnerd** [comment]
Just wanted to say again a big thank you for this.
