### ISSUE TITLE
Mobile layout - Recent changes checkboxes

### ISSUE THREAD

**Issue by Amousey** [Hutchy68/pivot#96]
### Setup

- Safari on ios13.3
- MediaWiki version: 1.31.7
- Database version: MariaDB 10.1.44-0
- PHP version: MariaDB 7.0.33-0
- Pivot version: 2.2.0

### Issue 
Recent Changes page checkboxes for Invert Namespace and Associated Namespace don't wrap correctly on mobiles or narrow screens, making it impossible to work out which checkbox is for which of the two options. 

Labels and their corresponding checkboxes are typically on different lines to each other.
This can be seen on [https://pivot.wikiproject.net/wiki/Special:RecentChanges pivot demo]

**Comment by Hutchy68** [comment]
This is what I see. 

![815FE257-4B5E-43EB-8AA7-F95E48FF4137](https://user-images.githubusercontent.com/3527469/79282914-5aa88d80-7e84-11ea-9688-bd7a770fb702.jpeg)

**Comment by Hutchy68** [comment]
So looking at this more, it is the output from MW which makes it hard to fix. Outputting, input, label, input, label, etc. without wrapping them in some type of controllable grouping is BAD layout output. MW 1.34 addresses this somewhat with the oo-ui widget for creating filters, etc. This will be even a bigger headache.

Closing as there was no response in 4 month and in MW 1.31 it would be a won't fix. MW should improve the output.
