### ISSUE TITLE
[Enhancement] Left-menu search (on mobile widths only) doesn't auto-complete

### ISSUE THREAD

**Issue by designnerd** [Hutchy68/pivot#98]
### Setup

- Browsers and versions: All
- MediaWiki version: All
- Database version: N/A
- PHP version: All
- Pivot version: All
- Extension version (if connected to the issue): Not related, not significant (displays the same behavior on Pivot demos)

### Issue

The left-sidebar search field auto-completes with MediaWiki default behavior, it will offer suggestions for known pages as characters are typed in; however, in mobile views when the left-sidebar slides in and out, auto-complete no longer functions on this field. Is this something that can be added (if it wouldn't be too difficult to implement)? 

Also, is there a place to donate to its development? Would be nice to be able to support it a bit. :)

Thanks in advance! :)

**Comment by Hutchy68** [comment]
Fixed, I hope in https://github.com/Hutchy68/pivot/compare/develop...login-improvements

Please fetch and checkout branch login-improvements.

**Comment by Hutchy68** [comment]
Merged into `develop` branch. No replies on issue, so closing. Thanks for reporting.

**Comment by designnerd** [comment]
Thanks for fixing it, much appreciated!
